print("Hello, day la chuong trinh pythonCatulator")
print("Ban muon thuc hien phep tinh gi ?")
print("neu la phep tinh nhan")
print("Moi ban nhap cac gia tri.")
a = int(input("gia tri thu nhat:" ))
b = int(input("gia tri thu hai :"))
print("Gia tri la %d" %(a*b))
print("neu la phep tinh cong")
a = int(input("gia tri thu nhat:" ))
b = int(input("gia tri thu hai :"))
print("Gia tri la %d" %(a+b))